services:
  synapse:
    image: xdillfrescott/synapse:latest
    container_name: synapse
    restart: always
    depends_on:
      - db
    ports:
      - "8008:8008"
    volumes:
      - "./data:/data"

  db:
    restart: always
    image: postgres:17
    container_name: maindb
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <password>
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./db_data:/var/lib/postgresql/data